# Generated by Django 3.2 on 2021-06-30 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('id_abogado', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria_abog', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DatosAbogado',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_abogado', models.CharField(max_length=15)),
                ('universidad', models.CharField(max_length=20)),
                ('años_experiencia', models.IntegerField(null=True)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abogado')),
            ],
        ),
    ]
