# Generated by Django 3.2 on 2021-06-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosabogado',
            old_name='años_experiencia',
            new_name='annios_experiencia',
        ),
    ]
