# Generated by Django 3.2 on 2021-06-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_años_experiencia_datosabogado_annios_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosabogado',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
